repos:
  - repo: local
    hooks:
      - id: lint-code
        name: Lint Python Code with Pylint
        entry: bash -c "pylint --ignore-patterns='.*migrations.*' $(git ls-files '*.py')"
        language: system
        pass_filenames: false
        always_run: true
