version: '3.8'
services:
  django:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"  # Expose Django on port 8000
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    depends_on:
      - redis  # Ensure Redis starts before Django
    environment:
      - REDIS_HOST=redis  # Host of the Redis service defined in docker-compose
      - REDIS_PORT=6379  # Redis default port

  redis:
    image: redis:latest  # Using the official Redis image
    container_name: redis_server
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - backend  # Both services will share this network

networks:
  backend:
    driver: bridge  # Default network mode

volumes:
  redis_data:
    driver: local  # Persistent storage for Redis data
